const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");

const root = path.resolve(__dirname, "..");
const read = rel => fs.readFileSync(path.join(root, rel), "utf8");

const app = read("src/App.vue");
const api = read("src/admin/adminApi.js");
const workload = read("src/components/experiment/WorkloadStage.vue");
const login = read("src/components/admin/AdminLogin.vue");
const dashboard = read("src/components/admin/AdminDashboard.vue");
const overview = read("src/components/admin/AdminOverview.vue");
const metricSummaryTable = read("src/components/admin/AdminMetricSummaryTable.vue");
const participantDetails = read("src/components/admin/AdminParticipantDetails.vue");
const chart = read("src/components/admin/AdminMetricChart.vue");
const academicMetricChart = read("src/components/admin/AdminAcademicMetricChart.vue");
const subjectiveChart = read("src/components/admin/AdminAcademicSubjectiveChart.vue");
const overallChart = read("src/components/admin/AdminAcademicOverallChart.vue");
const taskChart = read("src/components/admin/AdminAcademicTaskChart.vue");
const demoData = read("src/admin/adminDemoData.js");
const figureUtils = read("src/components/admin/academicFigureUtils.js");
const adminCss = read("src/components/admin/admin.css");

assert.match(app, /window\.location\.pathname/);
assert.match(app, /AdminLogin/);
assert.match(app, /AdminDashboard/);
assert.match(app, /AdminOverview/);
assert.match(app, /isAdminAnalysisRoute/);
assert.match(app, /\/admin\/analysis/);
assert.match(api, /withCredentials\s*:\s*true/);
assert.match(api, /\/admin\/login/);
assert.match(login, /username/);
assert.match(login, /password/);
assert.match(dashboard, /summary/);
assert.match(dashboard, /论文分析/);
assert.match(dashboard, /模拟数据/);
assert.match(dashboard, /AdminAcademicOverallChart/);
assert.match(dashboard, /AdminAcademicTaskChart/);
assert.match(dashboard, /AdminParticipantDetails/);
assert.match(dashboard, /participantDetails/);
assert.match(dashboard, /participantTasks/);
assert.match(demoData, /24/);
assert.match(demoData, /coolwarm|COOLWARM/);
assert.match(dashboard, /普通总览/);
assert.match(overview, /实验总览/);
assert.match(overview, /普通总览/);
assert.match(overview, /论文分析/);
assert.match(overview, /summary/);
assert.match(overview, /<AdminMetricSummaryTable/);
assert.match(overview, /participant-details/);
assert.match(overview, /查看该参与者完整数据/);
assert.match(participantDetails, /item_start_time/);
assert.match(participantDetails, /physical_demand/);
assert.equal((overview.match(/<AdminMetricSummaryTable\b/g) || []).length, 4);
assert.match(api, /data-quality/);
assert.doesNotMatch(dashboard, /:series="metric\("/);
assert.doesNotMatch(dashboard, /@click="download\("/);
assert.match(dashboard, /analysis/);
for (const label of ["CTIA", "CTIRT", "CRA", "ACA", "CLA", "CLT", "Reading Continuity", "Comment Accessibility", "NASA-TLX", "数据完整性", "导出", "重置参与者"]) {
  assert.match(dashboard, new RegExp(label));
}
assert.match(dashboard, /导出分析 CSV/);
assert.match(dashboard, /导出分析 JSON/);
assert.match(dashboard, /导出原始事件 CSV/);
assert.match(dashboard, /导出原始事件 JSON/);
assert.match(dashboard, /download\("csv", "events"\)/);
assert.match(api, /dataset/);
assert.match(api, /URLSearchParams/);
assert.match(chart, /observations/);
assert.match(chart, /ci95/);
assert.match(academicMetricChart, /values\.length\s*>=\s*4/);
assert.match(academicMetricChart, /small samples|sample size|interim/i);
assert.match(academicMetricChart, /RAMP_WIDTH\s*=\s*240/);
assert.match(academicMetricChart, /RAMP_LABEL_OFFSET\s*=\s*2\.1/);
assert.match(academicMetricChart, /RAMP_LABEL_Y\s*=\s*RAMP_Y\s*-\s*RAMP_LABEL_OFFSET/);
assert.match(academicMetricChart, /rampX|metricRampX/);
assert.match(academicMetricChart, /higherIsBetter === false.*text-anchor=\"start\"|text-anchor=\"start\".*higherIsBetter === false/s);
assert.match(academicMetricChart, /higherIsBetter !== false.*text-anchor=\"end\"|text-anchor=\"end\".*higherIsBetter !== false/s);
assert.match(overallChart, /overall completion time|Overall completion time|整体完成时间/);
assert.match(overallChart, /scatter|circle/);
assert.match(overallChart, /ci95|confidence/i);
assert.match(overallChart, /academic-overall-figure/);
assert.match(overallChart, /coolwarmColor|coolwarm/i);
assert.match(overallChart, /50/);
assert.match(overallChart, /studentTCritical|tCritical|t\.ppf/i);
assert.match(overallChart, /spreadEqualValues|equalValues/i);
assert.match(overallChart, /Lower is better/);
assert.match(overallChart, /RAMP_LABEL_OFFSET\s*=\s*2\.1/);
assert.match(overallChart, /timeRampLabelY\s*=\s*rampY\s*-\s*RAMP_LABEL_OFFSET/);
assert.match(overallChart, /CONDITION_LABELS|conditionLabel/);
assert.match(overallChart, /TE:\s*"TE"/);
assert.match(overallChart, /CS:\s*"CS"/);
assert.match(overallChart, /SE:\s*"SE"/);
assert.match(overallChart, /BL:\s*"BL"/);
assert.match(overallChart, /r="2\.645751"/);
assert.match(overallChart, /Higher is better/);
assert.match(overallChart, /viewBox="0 0 854\.27125 342\.566363"/);
assert.match(overallChart, /PLOT_BOTTOM \+ 28/);
assert.match(overallChart, /TIME_X\s*=\s*21\.77125/);
assert.match(overallChart, /ACCURACY_X\s*=\s*460\.821816/);
assert.match(overallChart, /PLOT_WIDTH\s*=\s*392\.009434/);
assert.match(overallChart, /accuracyDomain|0\.475/);
assert.match(overallChart, /timeXDomain|timeBounds|time_low/);
assert.match(overallChart, /coolwarmLut|COOLWARM_LUT|#5977e3/);
assert.match(taskChart, /Article/);
assert.match(taskChart, /Comment/);
assert.match(taskChart, /scatter|circle/);
assert.match(taskChart, /academic-task-figure/);
assert.match(taskChart, /conditionColors|coolwarm/i);
assert.match(taskChart, /#536edd/);
assert.match(taskChart, /#b3cdfb/);
assert.match(taskChart, /#f5c0a7/);
assert.match(taskChart, /#d0473d/);
assert.match(taskChart, /academic-figure-legend|legend/i);
assert.match(taskChart, /academic-task-legend-ci/);
assert.match(taskChart, /academic-task-legend-cap/);
assert.match(taskChart, /350\.7975.*406\.230313.*461\.8975.*517\.324063/s);
assert.doesNotMatch(adminCss, /\.academic-center,\s*\.academic-task-center\s*\{[^}]*fill:\s*#111/s);
assert.match(adminCss, /\.academic-task-center\s*\{\s*stroke:\s*#000/);
assert.match(taskChart, /studentTCritical|tCritical|t\.ppf/i);
assert.match(taskChart, /viewBox="0 0 916\.086406 320\.917469"/);
assert.match(taskChart, /TASK_PLOT_TOP|PLOT_TOP\s*=\s*63\.832/);
assert.match(taskChart, /PLOT_BOTTOM \+ 24/);
assert.doesNotMatch(taskChart, /PLOT_BOTTOM \+ 32/);
assert.match(taskChart, /Math\.sin/);
assert.match(taskChart, /TE:\s*"TE"/);
assert.match(taskChart, /CS:\s*"CS"/);
assert.match(taskChart, /SE:\s*"SE"/);
assert.match(taskChart, /BL:\s*"BL"/);
assert.match(taskChart, /- 2\.5/);
assert.match(dashboard, /AdminAcademicMetricChart/);
assert.match(dashboard, /chartType:\s*"bar"/);
assert.match(dashboard, /chartType:\s*"boxplot"/);
assert.match(dashboard, /chart-type="horizontal-bar"/);
assert.match(academicMetricChart, /chartType/);
assert.match(academicMetricChart, /academic-bar/);
assert.match(academicMetricChart, /academic-box/);
assert.match(academicMetricChart, /academic-horizontal-bar/);
assert.match(academicMetricChart, /errorbar|error-line|ci95/);
assert.match(dashboard, /核心结果图/);
assert.match(dashboard, /阅读行为图/);
assert.match(dashboard, /评论交互图/);
assert.match(dashboard, /主观评价图/);
assert.match(dashboard, /AdminAcademicSubjectiveChart/);
assert.match(dashboard, /NASA-TLX/);
assert.match(subjectiveChart, /Mental Demand/);
assert.match(subjectiveChart, /Physical Demand/);
assert.match(subjectiveChart, /Temporal Demand/);
assert.match(subjectiveChart, /Performance/);
assert.match(subjectiveChart, /Effort/);
assert.match(subjectiveChart, /Frustration/);
assert.match(subjectiveChart, /2x3|grid-template-columns|subjective-panel/);
assert.match(subjectiveChart, /1, 2, 3, 4, 5, 6, 7/);
assert.match(subjectiveChart, /formatAxisValue/);
assert.match(subjectiveChart, /panelCaption/);
assert.doesNotMatch(subjectiveChart, /academic-subjective-panel-title/);
assert.match(workload, /min="1" max="7" step="1"/);
assert.match(workload, /mental_demand: 4/);
assert.match(subjectiveChart, /global.*(?:direction|legend)|subjective-global/i);
assert.match(subjectiveChart, /Lower is better/);
assert.match(subjectiveChart, /SUBJECTIVE_FIGURE_WIDTH\s*=\s*1080/);
assert.match(subjectiveChart, /SUBJECTIVE_RAMP_WIDTH\s*=\s*180/);
assert.match(subjectiveChart, /SUBJECTIVE_RAMP_X\s*=\s*\(SUBJECTIVE_FIGURE_WIDTH\s*-\s*SUBJECTIVE_RAMP_WIDTH\)\s*\/\s*2/);
assert.match(subjectiveChart, /SUBJECTIVE_RAMP_LABEL_OFFSET\s*=\s*2\.1/);
assert.match(subjectiveChart, /SUBJECTIVE_RAMP_LABEL_Y\s*=\s*SUBJECTIVE_RAMP_Y\s*-\s*SUBJECTIVE_RAMP_LABEL_OFFSET/);
assert.match(subjectiveChart, /globalDirectionIsLower/);
assert.match(subjectiveChart, /:text-anchor=\"globalDirectionIsLower \? 'start' : 'end'\"/);
assert.match(subjectiveChart, /:x=\"globalDirectionIsLower \? SUBJECTIVE_RAMP_X : SUBJECTIVE_RAMP_X \+ SUBJECTIVE_RAMP_WIDTH\"/);
assert.doesNotMatch(subjectiveChart, /item\.higherIsBetter === false \? "← Lower is better"/);
assert.match(dashboard, /Performance.*higherIsBetter: false/);
assert.match(subjectiveChart, /RC|CA/);
assert.doesNotMatch(dashboard, /AdminAcademicMetricChart v-for="item in subjectiveMetrics"/);
assert.match(subjectiveChart, /academic-observation|circle/);
assert.match(subjectiveChart, /exportSvgAsPng/);
assert.match(subjectiveChart, /导出 PNG/);
assert.doesNotMatch(adminCss, /academic-metric-chart-scroll\s*\{[^}]*overflow-x\s*:\s*auto/s);
assert.doesNotMatch(adminCss, /academic-metric-svg\s*\{[^}]*min-width/s);
assert.match(dashboard, /偏好结果图/);
assert.match(taskChart, /academic-task-mean-line/);
assert.match(taskChart, /taskMeanPoints/);
assert.doesNotMatch(taskChart, /<polyline\b[^>]*v-for="[^"]+"[^>]*v-if="[^"]+"/);
assert.match(taskChart, /r="2\.345208"/);
assert.match(figureUtils, /#536edd|#5977e3|coolwarmLut|COOLWARM_LUT/);
assert.match(app, /ParticipantPicker/);
assert.match(app, /ReadingStage/);
assert.doesNotMatch(app, /participant_id.*admin/i);

const exportUtil = read("src/components/admin/adminChartExport.js");
assert.match(exportUtil, /exportSvgAsPng/);
assert.match(exportUtil, /XMLSerializer/);
assert.match(exportUtil, /pageStyles/);
assert.match(exportUtil, /cssRules/);
assert.match(exportUtil, /toBlob/);
assert.match(exportUtil, /image\/png/);
assert.match(exportUtil, /download/);
assert.doesNotMatch(exportUtil, /application\/pdf/);
assert.match(overallChart, /ref="chartSvg"/);
assert.match(overallChart, /exportSvgAsPng/);
assert.match(overallChart, /导出 PNG/);
assert.match(taskChart, /ref="chartSvg"/);
assert.match(taskChart, /exportSvgAsPng/);
assert.match(taskChart, /导出 PNG/);
assert.match(chart, /metric-figure/);
assert.match(chart, /exportSvgAsPng/);
assert.match(chart, /导出 PNG/);
assert.match(chart, /coolwarmColor|coolwarm/i);
assert.match(chart, /Lower is better/);
assert.match(chart, /Higher is better/);
assert.doesNotMatch(chart, /数值越高越好|数值越低越好/);

assert.match(overallChart, /values\.length\s*>=\s*4/);
assert.match(overallChart, /small samples|sample size|interim/i);

// Compact paper-analysis layout guards: figures should use the page width without
// generous inter-panel whitespace or a horizontal overflow fallback.
assert.match(adminCss, /\.admin-dashboard\s*\{[^}]*padding:\s*24px 22px 36px/s);
assert.match(adminCss, /\.admin-dashboard-header\s*\{[^}]*margin-bottom:\s*14px/s);
assert.match(adminCss, /\.admin-section\s*\{\s*margin-top:\s*12px/s);
assert.match(adminCss, /\.admin-section h2\s*\{[^}]*margin:\s*0 0 6px/s);
assert.match(adminCss, /\.admin-section-description\s*\{\s*margin:\s*-2px 0 6px/s);
assert.match(adminCss, /\.admin-analysis-toolbar\s*\{[^}]*margin:\s*-8px 0 14px/s);
assert.match(adminCss, /\.admin-metric-grid\s*\{[^}]*gap:\s*8px/s);
assert.match(adminCss, /\.admin-section\s*\{\s*margin-top:\s*12px/s);
assert.match(adminCss, /\.academic-overall-figure, \.academic-task-figure\s*\{[^}]*margin-top:\s*2px;[^}]*padding:\s*0/s);
assert.match(adminCss, /\.academic-task-chart\s*\{\s*margin-top:\s*8px/s);
assert.match(adminCss, /\.academic-metric-figure\s*\{[^}]*margin-top:\s*2px;[^}]*padding:\s*0/s);
assert.match(adminCss, /\.academic-subjective-figure\s*\{[^}]*margin-top:\s*2px;[^}]*padding:\s*0/s);
assert.match(adminCss, /\.academic-figure-toolbar\s*\{[^}]*min-height:\s*22px/s);
assert.match(adminCss, /\.academic-chart-caption\s*\{\s*margin:\s*0[^}]*line-height:\s*1\.25/s);
assert.match(adminCss, /\.academic-export-button\s*\{[^}]*padding:\s*4px 8px/s);
assert.match(adminCss, /\.academic-metric-table-row\s*\{[^}]*gap:\s*8px;[^}]*padding:\s*3px 0 0/s);
assert.match(subjectiveChart, /const PANEL_HEIGHT = 286/);
assert.match(subjectiveChart, /const PANEL_GAP_Y = 16/);
assert.match(subjectiveChart, /const figureHeight = computed\(\(\) => props\.metrics\.length > 3 \? 612 : 316\)/);

console.log("admin dashboard source checks passed");

assert.match(overview, /article_order/);
assert.match(overview, /dataSection/);
assert.match(overview, /dataSection:\s*"progress"/);
assert.match(overview, /查看指标/);
assert.match(overview, /<option value="progress">实验进度<\/option>/);
assert.doesNotMatch(overview, /dataSection:\s*"all"/);
assert.match(overview, /Object\.assign\(filters,\s*\{[^}]*dataSection:\s*"progress"/s);
assert.match(overview, /偏好排序/);
assert.match(overview, /偏好理由/);
assert.match(overview, /半结构化访谈/);
assert.match(overview, /NASA-TLX Mental Demand/);
assert.match(overview, /Comment Interaction Count/);
assert.match(overview, /mean/);
assert.match(metricSummaryTable, /median/);
assert.match(metricSummaryTable, /stddev/);
assert.match(overview, /admin-filter-panel/);
assert.match(overview, /adminApi\.summary\(apiFilters/);
assert.match(overview, /AdminParticipantDetails/);
assert.match(overview, /participantDetails/);
assert.match(overview, /<AdminParticipantDetails\s+v-if="filters\.participant_id"/);
assert.match(participantDetails, /参与者详细数据/);
assert.match(participantDetails, /逐题回答明细/);
assert.match(participantDetails, /评论交互事件/);

const overviewDemoDataSource = read("src/admin/adminDemoData.js");
assert.match(overview, /使用模拟数据预览/);
assert.match(overview, /showDemoData/);
assert.match(overview, /buildDemoOverviewSummary/);
assert.match(overview, /DEMO_OVERVIEW_SUMMARY/);
assert.match(overviewDemoDataSource, /DEMO_OVERVIEW_SUMMARY/);
assert.match(overviewDemoDataSource, /buildDemoOverviewSummary/);
assert.match(overviewDemoDataSource, /expected_participants:\s*24/);
assert.match(overviewDemoDataSource, /article_sessions_expected:\s*expectedSessions/);
assert.match(overviewDemoDataSource, /responses:[\s\S]*total:\s*responseCount/);
assert.match(overviewDemoDataSource, /preference_reason_submitted/);
assert.match(overviewDemoDataSource, /interviews_expected:\s*24/);
// A complete article sequence scopes participants, but it does not reduce each
// selected participant to a single article session.
assert.match(overviewDemoDataSource, /const hasSessionFilter = Boolean\(filters\.article_id \|\| filters\.condition \|\| filters\.article_order\)/);
// Selecting a participant must keep the four article blocks visible in the
// preview, even when another session filter is still selected.
assert.match(overviewDemoDataSource, /const DEMO_ARTICLE_PLANS = \[\s*\[/);
assert.match(overviewDemoDataSource, /const slots = demoArticlePlanForParticipant\(participantIndex\)/);
assert.match(overviewDemoDataSource, /const participantDetails = slots\.map/);
assert.match(overviewDemoDataSource, /ignores article\/condition\/position\/status filters/);
assert.match(overview, /不会写入 SQLite/);

// Article display numbers are intentionally decoupled from internal article IDs.
assert.match(overview, /articleDisplayLabels/);
assert.match(overview, /A02.*01|01.*A02/);
assert.match(overview, /A03.*02|02.*A03/);
assert.match(overview, /A04.*03|03.*A04/);
assert.match(overview, /A07.*04|04.*A07/);
assert.match(overview, /articleSequenceOptions/);
assert.match(overview, /01 → 02 → 03 → 04/);
assert.match(overview, /02 → 03 → 04 → 01/);
assert.match(overview, /03 → 04 → 01 → 02/);
assert.match(overview, /04 → 01 → 02 → 03/);
assert.match(overview, /文章位置/);
assert.match(overview, /文章顺序（按参与者分组）/);
assert.match(overview, /article_sequence/);
assert.match(participantDetails, /articleDisplayLabels/);

// Article-sequence scope is participant-group-wide: it must not remain narrowed
// by a previously selected participant, and selecting a participant switches
// back to participant-specific scope.
assert.match(overview, /@change="handleParticipantFilterChange"/);
assert.match(overview, /@change="handleSequenceFilterChange"/);
assert.match(overview, /function handleParticipantFilterChange/);
assert.match(overview, /function handleSequenceFilterChange/);
assert.match(overview, /filters\.participant_id = ""/);
assert.match(overview, /filters\.article_sequence = ""/);
assert.match(overview, /if \(next\.article_sequence\) delete next\.participant_id/);

const participantOverview = read("src/components/admin/AdminParticipantOverviewTable.vue");
assert.match(overview, /AdminParticipantOverviewTable/);
assert.match(overview, /participantOverview/);
assert.match(overview, /view-participant/);
assert.match(participantOverview, /P01|participant_id/);
assert.match(participantOverview, /查看详情/);
assert.match(participantOverview, /article_sessions_completed/);
assert.match(participantOverview, /responses_count/);
assert.match(participantOverview, /preference_submitted/);
assert.match(demoData, /participant_overview/);
